### ISSUE TITLE
Link to this information from the API Technical Specification page

### ISSUE THREAD

**Issue by francisbarton** [OrdnanceSurvey/tile-name-derivation#1]
Hi there

I have been building a client in R for your Maps API, to generate custom raster basemaps using your map tiles.
I couldn't work out what I was doing wrong, because I checked all my calculations but I was still returning the wrong tiles (in 27700) for a given BNG easting and northing reference.

I was working purely with the information I could glean from the API [Technical Specification](https://osdatahub.os.uk/docs/wmts/technicalSpecification) page, and I spent quite a bit of time using a trial and error approach to try to find out things like how many tile columns and rows there are at each zoom level and so on.

I had assumed that your map tile grid would start at (0,0)m and go to (7e5, 1.3e6)m but I soon discovered that the tiles extend much further than the BNG per se. But by how much?

Having found this repo (and your others), and tools like the [Tile Matrix Comparison](https://labs.os.uk/public/os-api-resources/tile-matrix-compare.html), I realise I could have saved a lot of time and puzzlement if I had found these earlier. The Tile Matrix tool is really helpful for being able to see exactly what area the tile matrix covers.

My request is that these resources be linked to, or at least mentioned, on the Tech Spec page. It might help others in future.

Knowing that the tile matrix has a false origin at (-238375.0, 1376256.0) is really crucial information, I think.
Thanks.

**Comment by tmnnrs** [comment]
Hi @francisbarton. Thank you so much for the feedback. We [OS] are constantly looking to review the resources we provide (and their discoverability) - and your comments are actually very timely as we start to look at the next phase of the Data Hub. I would also be very interested in hearing more about the R client you are building (as it is something we are increasingly being asked about).

**Comment by francisbarton** [comment]
Hi @tmnnrs I am really sorry I never got back to you on this.
I wanted to do some more work on my package before sharing it...

It's here, and still a work in progress of course but I'm really happy for you to point people to it:
[https://github.com/francisbarton/mapirosa/](https://github.com/francisbarton/mapirosa/)

The bit of code where the false origin was really useful is here:
https://github.com/francisbarton/mapirosa/blob/a7c504e6233128aa33d80511c30e734738a219be/R/generate_png_data.R#L100

(I spent ages trying to reverse engineer the secret to the tile coordinates before I discovered that!)
